import { defineNitroPlugin, useRuntimeConfig } from 'nitropack/runtime'
import { PgDataSourceManager, scanPgEntities } from '@opencowstudio/pg-core'
import type { PgDataSourceConfig } from '@opencowstudio/pg-core'

// Virtual module generated by the module at build time: it imports every
// **/entities/*.ts file (transformed by Vite/Nitro with native decorator
// support) and re-exports them as `entityModules`.
// @ts-ignore virtual module provided by @opencowstudio/nuxt-pg at build time
import { entityModules } from '#opencowstudio/entities'

scanPgEntities(entityModules as Record<string, unknown>[])

// Lazily-built singleton so every server request shares one set of pools.
let manager: PgDataSourceManager | null = null

/**
 * Return the shared multi-database datasource manager.
 *
 * The manager is constructed once from the server-only runtime config
 * (`runtimeConfig.pg`). Entities resolve their connection via
 * `usePgDataSourceManager().get(entity.dbName)`.
 */
export function usePgDataSourceManager(): PgDataSourceManager {
  if (!manager) {
    const config = useRuntimeConfig().pg as unknown as PgDataSourceConfig
    manager = new PgDataSourceManager(config)
  }
  return manager
}

export default defineNitroPlugin(() => {
  // Build the pools eagerly at server start so connection errors surface early.
  usePgDataSourceManager()
})
