// Ambient declaration for the build-time manifest injected via the
// `#pg-manifest` alias (generated by the module setup in `src/index.ts`).
declare module '#pg-manifest' {
  import type { PgConfigMetadata } from '@opencowstudio/pg-core'

  export const pgConfig: PgConfigMetadata | null
}
