// Ambient declaration for the build-time manifest injected via the
// `#pg-manifest` alias (generated by the module setup in `src/module.ts`).
declare module '#pg-manifest' {
  /**
   * Formatted JSON string of the `pg` namespace, or null when no config file
   * was found at build time. The runtime parses this back into a
   * `PgConfigMetadata` object.
   */
  export const pgConfigJson: string | null
}

declare module '#pg-entities-manifest' {
  /**
   * Formatted JSON string of the scanned entity collection, or an empty array
   * when no entities were found at build time. The runtime parses this back
   * into an array of `PgEntityRaw` objects.
   */
  export const pgEntitiesJson: string
}
