pool:
  max: 18
  min: 18
  idleTimeoutMillis: 600000
  maxLifetimeSeconds: 1800
databases:
  default:
    master:
      url: postgresql://localhost:5432/opencowstudio_dev
      username: postgres
      password: postgres
    slaves:
      - url: postgresql://localhost:5432/opencowstudio_dev
        username: postgres
        password: postgres
      - url: postgresql://localhost:5432/opencowstudio_dev
        username: postgres
        password: postgres
