// ---------------------------------------------------------------------------
// Entity operation contract (runtime)
//
// `PgEntityRepository<T, K>` is the CRUD surface the runtime implements for a
// single entity. Entity metadata resolution lives in `builder/parser.ts`
// (`parsePgEntity` / `parsePgEntities`), which is build-time only.
// ---------------------------------------------------------------------------

/**
 * Entity operation contract: the common CRUD surface for a single entity.
 *
 * `T` is the entity class, `K` the type of its primary key value (`string` or
 * `number`). The key property is fixed to `id`.
 */
export interface PgEntityRepository<T, K = string | number> {
  /** Insert a new row; the key is generated by the database. */
  insert(data: Omit<T, 'id'>): Promise<T>

  /** Update the row whose key equals `id` and return the stored entity. */
  update(id: K, data: Omit<T, 'id'>): Promise<T>

  /** Delete the row whose key equals `id`. */
  delete(id: K): Promise<void>

  /** Return the row whose key equals `id`, or `null` when it does not exist. */
  findById(id: K): Promise<T | null>
}
