import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  addServerPlugin,
  addTemplate,
  createResolver,
  defineNuxtModule,
  useLogger,
} from '@nuxt/kit'
import { parse as parseYaml } from 'yaml'
import { type PgConfigMetadata } from '@opencowstudio/pg-core'

export { generateGuid, generateId } from '@opencowstudio/pg-core'

const MODULE_NAME = '@opencowstudio/nuxt-pg'

export interface ModuleOptions {
  /**
   * Enable or disable the module
   * @default true
   */
  enabled?: boolean
  /**
   * Path to the PostgreSQL datasource configuration file (YAML). The path is
   * resolved relative to the Nuxt root directory. When the file exists it is
   * parsed into a `PgConfigMetadata` object at build time and baked into a
   * server-only manifest, so credentials never reach the client bundle.
   * @default 'pg.config.yaml'
   */
  configFile?: string
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: MODULE_NAME,
    configKey: 'pg',
    compatibility: {
      nuxt: '>=4.0.0',
    },
  },
  defaults: {
    enabled: true,
    configFile: 'pg.config.yaml',
  },
  async setup(options, nuxt) {
    if (!options.enabled) {
      return
    }

    const logger = useLogger(MODULE_NAME)
    const resolver = createResolver(import.meta.url)

    // Resolve the config file path relative to the Nuxt root directory.
    const configPath = resolve(nuxt.options.rootDir, options.configFile!)

    let pgConfig: PgConfigMetadata | null = null
    if (existsSync(configPath)) {
      logger.info(`Found pg config file: ${configPath}`)
      const raw = readFileSync(configPath, 'utf8')
      pgConfig = parseYaml(raw) as PgConfigMetadata
    } else {
      logger.warn(`No pg config file found at: ${configPath}`)
    }

    // Emit a build-time manifest carrying the parsed configuration so the Nitro
    // runtime can consume it without re-reading the YAML file at runtime.
    const manifest = addTemplate({
      filename: 'pg.manifest.ts',
      write: true,
      getContents: () =>
        [
          '// This file is auto-generated by @opencowstudio/nuxt-pg. Do not edit manually.',
          "import type { PgConfigMetadata } from '@opencowstudio/pg-core'",
          '',
          `export const pgConfig: PgConfigMetadata | null = ${JSON.stringify(pgConfig, null, 2)}`,
          '',
        ].join('\n'),
    })

    // Expose the manifest via alias. Nuxt forwards `nuxt.options.alias` into the
    // Nitro build, so the server plugin can resolve `#pg-manifest` as well.
    nuxt.options.alias['#pg-manifest'] = manifest.dst

    // Register the Nitro plugin that instantiates the datasource manager.
    addServerPlugin(resolver.resolve('./runtime/nitro/plugin'))
  },
})
