import { addTemplate } from '@nuxt/kit'
import type { Nuxt } from 'nuxt/schema'
import type { PgConfigMetadata } from '@opencowstudio/pg-core'

/** Alias under which the generated manifest is exposed to the runtime. */
export const PG_MANIFEST_ALIAS = '#pg-manifest'

/**
 * Emit a build-time manifest carrying the parsed configuration so the Nitro
 * runtime can consume it without re-reading the YAML file at runtime. Credentials
 * stay server-only and never reach the client bundle.
 *
 * Build-time only — this helper must never be imported from the runtime.
 *
 * @returns The destination path of the generated manifest template.
 */
export function registerPgManifest(nuxt: Nuxt, pgConfig: PgConfigMetadata | null): string {
  const manifest = addTemplate({
    filename: 'pg.manifest.ts',
    write: true,
    getContents: () =>
      [
        '// This file is auto-generated by @opencowstudio/nuxt-pg. Do not edit manually.',
        "import type { PgConfigMetadata } from '@opencowstudio/pg-core'",
        '',
        `export const pgConfig: PgConfigMetadata | null = ${JSON.stringify(pgConfig, null, 2)}`,
        '',
      ].join('\n'),
  })

  // Expose the manifest via alias. Nuxt forwards `nuxt.options.alias` into the
  // Nitro build, so the server plugin can resolve `#pg-manifest` as well.
  nuxt.options.alias[PG_MANIFEST_ALIAS] = manifest.dst
  return manifest.dst
}
