import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { addTemplate, useLogger } from '@nuxt/kit'
import type { Nuxt } from 'nuxt/schema'
import { parsePgEntities, type PgEntityRaw } from '@opencowstudio/pg-core'
import { findPgConfigFile, scanEntityPaths } from './scanner'
import { readPgConfigNamespace } from './yaml'

const MODULE_NAME = '@opencowstudio/nuxt-pg'

/** Alias under which the generated manifest is exposed to the runtime. */
export const PG_MANIFEST_ALIAS = '#pg-manifest'

/** Alias under which the generated entity manifest is exposed to the runtime. */
export const PG_ENTITIES_MANIFEST_ALIAS = '#pg-entities-manifest'

/**
 * Read the pg config file at build time, extract its `pg` namespace as a generic
 * JSON object, serialize it to a formatted JSON string, and bake that string
 * into a server-only manifest. The runtime parses the string back into metadata,
 * so the YAML file is never re-read at runtime and credentials never reach the
 * client bundle.
 *
 * Build-time only — this helper must never be imported from the runtime.
 *
 * @returns The destination path of the generated manifest template.
 */
export function registerPgManifest(nuxt: Nuxt, configFile: string): string {
  const logger = useLogger(MODULE_NAME)
  const configPath = findPgConfigFile(nuxt.options.rootDir, configFile)

  // The formatted JSON string of the `pg` namespace, or null when no config
  // is found so the runtime can skip datasource initialization.
  let pgConfigJson: string | null = null

  if (!configPath) {
    logger.warn(`No pg config file found at: ${resolve(nuxt.options.rootDir, configFile)}`)
  } else {
    logger.info(`Found pg config file: ${configPath}`)
    const raw = readFileSync(configPath, 'utf8')
    const pgNamespace = readPgConfigNamespace(raw)
    if (!pgNamespace) {
      logger.warn(`No \`pg\` namespace found in config file: ${configPath}`)
    } else {
      pgConfigJson = JSON.stringify(pgNamespace, null, 2)
      logger.info(`Pg config JSON:\n${pgConfigJson}`)
    }
  }

  const manifest = addTemplate({
    filename: 'pg.manifest.ts',
    write: true,
    getContents: () =>
      [
        '// This file is auto-generated by @opencowstudio/nuxt-pg. Do not edit manually.',
        '',
        `export const pgConfigJson: string | null = ${JSON.stringify(pgConfigJson)}`,
        '',
      ].join('\n'),
  })

  // Expose the manifest via alias. Nuxt forwards `nuxt.options.alias` into the
  // Nitro build, so the server plugin can resolve `#pg-manifest` as well.
  nuxt.options.alias[PG_MANIFEST_ALIAS] = manifest.dst
  return manifest.dst
}

/**
 * Scan the configured entity paths, convert every discovered entity class into
 * a `PgEntityRaw` by parsing its decorators statically (no module import, no
 * class instantiation), serialize the collection to a formatted JSON string,
 * and bake that string into a server-only manifest at build time.
 *
 * Build-time only — this helper must never be imported from the runtime.
 *
 * @returns The destination path of the generated manifest template.
 */
export async function registerPgEntityManifest(nuxt: Nuxt, entityPaths: string[]): Promise<string> {
  const logger = useLogger(MODULE_NAME)

  // Collect entity source files from the configured glob patterns.
  const files = await scanEntityPaths(nuxt.options.rootDir, entityPaths)
  logger.info(`Scanned ${files.length} entity file(s) from entity paths`)

  // Parse each entity class statically (via the TypeScript compiler API) into
  // its raw decorator metadata. Files that fail to parse are skipped with a
  // warning so a single bad entity does not abort the whole build.
  const entityRaws: PgEntityRaw[] = parsePgEntities(files, { skipInvalid: true })
  for (const raw of entityRaws) {
    logger.info(`Converted entity "${raw.className}" to PgEntityRaw`)
  }

  const pgEntitiesJson = JSON.stringify(entityRaws, null, 2)
  logger.info(`Pg entities JSON:\n${pgEntitiesJson}`)

  const manifest = addTemplate({
    filename: 'pg.entities.manifest.ts',
    write: true,
    getContents: () =>
      [
        '// This file is auto-generated by @opencowstudio/nuxt-pg. Do not edit manually.',
        '',
        `export const pgEntitiesJson: string = ${JSON.stringify(pgEntitiesJson)}`,
        '',
      ].join('\n'),
  })

  // Expose the entity manifest via alias. Nuxt forwards `nuxt.options.alias`
  // into the Nitro build, so the server plugin can resolve `#pg-entities-manifest`.
  nuxt.options.alias[PG_ENTITIES_MANIFEST_ALIAS] = manifest.dst
  return manifest.dst
}
