// ---------------------------------------------------------------------------
// Entity operation API — repository contract
//
// `PgEntityRepository<T, K>` is the runtime contract for operating on a single
// entity (one table): the common create / read / update / delete surface. It is
// implementation-agnostic — any class living next to a `PgDataSource` can
// implement it.
//
// `T` is the entity class, `K` the type of its primary key value (`string` or
// `number`). The key property is fixed to `id`.
// ---------------------------------------------------------------------------

export interface PgEntityRepository<T, K = string | number> {
  /** Insert a new row; the key is generated by the database. */
  insert(data: Omit<T, 'id'>): Promise<T>

  /** Update the row whose key equals `id` and return the stored entity. */
  update(id: K, data: Omit<T, 'id'>): Promise<T>

  /** Delete the row whose key equals `id`. */
  delete(id: K): Promise<void>

  /** Return the row whose key equals `id`, or `null` when it does not exist. */
  findById(id: K): Promise<T | null>
}
